#!/usr/bin/env bash
# installs and configures nginx web server to listen to port 80 and
# serves a page with content `Hello World!` when / is querried

apt-get -y update
apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html && \
sudo chmod -R 755 /var/www/html && \
echo "Hello World!" > /var/www/html/index.html
service nginx restart
