#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.

sigterm_handler() {
	echo "Killed"
	exit 0
}

trap 'sigterm_handler' SIGTERM

while :; do
	echo "To infinity and beyond"
	sleep 2
done
