#!/usr/bin/env bash
# Bash script that displays:
# -The content of the current directory
# -In a list format
# -Where only the part of the name after the first dash is displayed

for file in $(ls); do
	if [ -f "$file" ]; then
		part_after_dash="${file#*-}"
		echo "$part_after_dash"
	fi
done
